
RUN_DIR: "LightPuromycinMinusNoERCC" # The Directory to store results in
CountFile: "initialData/LightOnlyDataset.csv" # The counts file to use
tag2Name: "initialData/locusTagtoGeneName.csv"
initial_sep: ","
# The Counts file will be split at _ seperator and all terms will become conditions
column_mapping: ["Puromycin", "Fraction", "Replicate"]

design: "~ Replicate + Fraction"

# Will be zipped together. Can be run for multiple conditions. Must be levels of last Factor
conditions: ["M", "C", "M"]
baselines: ["TC", "TC", "C"]

drop_condition: {"Puromycin": ["plusP"]}
blacklisted_samples: False

use-spike-ins: False
spike-in-pattern: "ERCC"

use-housekeeping: False
housekeeping: ""

GOTermDir: "GOTerms"
tax_id: 11117
genus: "Synechocystis"
species: "sp"

# GOEnrichment Settings
log2FCCutOff: 0.8
pAdjCutOff: 0.05
minGSSize: 30
maxGSSize: 500


# Setting for GO Term enrichment reduction. Will remove redundant GO Terms via Calculating their Semantic Similarity and
# Clustering via DBScan
cluster-eps: 0.25 # epsilon to use for DBScan Clustering
sort_method: "p.adjust" # Which column of the Enrichment Table to use for sorting. Will use the first from a cluster and drop others
ascending: True


# Plotting
highlight: {"GOI": ["purple", ["psbA2", "rnpB", "pilA1", "psaA", "cmpC", "pixG", "pilB", "pixG;  pisG;  taxP1;  rer1", "kpsM"]]}
upColor: "rgb(255,0,0)"
downColor: "rgb(255,165,0)"
normalColor: "rgb(199,199,199)"